#!/bin/bash

#Base de datos de errores
##Impares == errores (--error)
##Pares == Información (--info)

#El usuario presiona el botón de cancelar o volver.
1:Error. No se realizaron los cambios.
#El usuario pulsa en Aceptar y se realiza la modificación.
2:Cambios realizados correctamente.
#El usuario pulsa en Aceptar y no ha seleccionado ninguna opción.
3:Error. Seleccione una opción válida.
#Se crea correctamente la contraseña.
4:Contraseña creada con éxito.
#El usuario selecciona una imagen con una extensión no válida.
5:Error. Seleccione una imagen válida.
#El usuario no ha rellenado todos los campos necesarios.
7:Error. Rellene todos los campos.
#Error desconocido.
9:Error. La contraseña no fue creada.


  #Listado de mensajes de error (antiguo) ¡NO BORRAR PARA TENER UNA REFERENCIA!
  #case $codigoError in
  #	0)
  #		zenity --info --text "Cambios realizados correctamente."
  #	;;
  #	1)
  #		zenity --error --text "No se realizaron cambios."
  #	;;
  #	2)
  #		zenity --error --text "Selecciona una imagen válida."
  #	;;
  #	3)
  #		zenity --error --text "Seleccione una opción válida."
  #	;;
  #esac
    
##############-Cosas que faltan-#####################
#Codigo de errores
#Logs --> Garcia y Cabot
#Ordenar Codigo (Cambiar nombre de variables)
#####################################################

##############-Cosas "hechas"-#####################
#Instalador (a falta de probar que funciona)
#Menú pirncipal (a falta de los logs)
#####################################################
