#!/bin/bash

#Base de datos de errores
##Impares == errores (--error)
##Pares == Información (--info)

#El usuario presiona el botón de cancelar o volver.
1:Error. No se realizaron los cambios.
#El usuario pulsa en Aceptar y se realiza la modificación.
2:Cambios realizados correctamente.
#El usuario pulsa en Aceptar y no ha seleccionado ninguna opción.
3:Error. Seleccione una opción válida.
#Se crea correctamente la contraseña.
4:Contraseña creada con éxito.
#El usuario selecciona una imagen con una extensión no válida.
5:Error. Seleccione una imagen válida.
#Se elimina correctamente la contraseña.
6:Contraseña eliminada con éxito.
#El usuario no ha rellenado todos los campos necesarios.
7:Error. Rellene todos los campos.
#Se modifica correctamente la contraseña.
8:Contraseña modificada con éxito.
#Error desconocido al crear la contraseña.
9:Error. La contraseña no fue creada a causa de un error desconocido.
#Error al acceder al menú de nueva contraseña porque ya existía una previamente.
11:Error. Ya existe una contraseña. Para modificar la contraseña existente seleccione la opción "Modificar contraseña".
#Error al acceder al menú de eliminar contraseña si no hay una establecida.
13:Error. No hay establecida ninguna contraseña actualmente.
#Error desconocido al eliminar la contraseña.
15:Error. La contraseña no fue eliminada a causa de un error desconocido.
#Error desconocido al modificar la contraseña.
17:Error. La contraseña no fue modificada a causa de un error desconocido.



  #Listado de mensajes de error (antiguo) ¡NO BORRAR PARA TENER UNA REFERENCIA!
  #case $codigoError in
  #	0)
  #		zenity --info --text "Cambios realizados correctamente."
  #	;;
  #	1)
  #		zenity --error --text "No se realizaron cambios."
  #	;;
  #	2)
  #		zenity --error --text "Selecciona una imagen válida."
  #	;;
  #	3)
  #		zenity --error --text "Seleccione una opción válida."
  #	;;
  #esac
    
##############-Cosas que faltan-#####################
#Codigo de errores
#Logs --> Garcia y Cabot
#Ordenar Codigo (Cambiar nombre de variables)
#####################################################

##############-Cosas "hechas"-#####################
#Instalador (a falta de probar que funciona)
#Menú pirncipal (a falta de los logs)
#####################################################
